import { type ChildProfile } from "./types";

export const demoProfiles: ChildProfile[] = [
  {
    id: -1,
    nickname: "小星星",
    age_range: "age_3_4",
    age_range_label: "3-4岁",
    reading_level: "starter",
    reading_level_label: "启蒙期",
    interest_tags: ["animals", "fairy_tale", "music"],
    education_goals: ["language", "emotion"],
    default_character: "star-child",
    default_voice: "warm-mom",
    default_art_style: "watercolor",
    is_default: true,
    status: "active",
  },
  {
    id: -2,
    nickname: "豆豆",
    age_range: "age_5_6",
    age_range_label: "5-6岁",
    reading_level: "growing",
    reading_level_label: "成长期",
    interest_tags: ["nature", "friendship", "adventure"],
    education_goals: ["habit", "social"],
    default_character: "forest-friend",
    default_voice: "story-dad",
    default_art_style: "crayon",
    is_default: false,
    status: "active",
  },
  {
    id: -3,
    nickname: "小果",
    age_range: "age_7_8",
    age_range_label: "7-8岁",
    reading_level: "independent",
    reading_level_label: "独立阅读",
    interest_tags: ["space", "science", "fairy_tale"],
    education_goals: ["courage", "creativity"],
    default_character: "little-captain",
    default_voice: "clear-teacher",
    default_art_style: "bedtime",
    is_default: false,
    status: "active",
  },
];
