import { type StorySummary } from "@/entities/story";

export const demoStories: StorySummary[] = [
  {
    id: 1,
    owner_user_id: null,
    source_type: "system",
    title: "想念月亮的小狐狸",
    summary: "适合睡前共读的温柔故事，帮助孩子表达想念和感谢。",
    cover_url: null,
    age_range_ids: [2],
    theme_ids: [1],
    education_goal_ids: [1],
    language: "zh",
    access_level: "free",
    publish_status: "published",
    view_count: 1200,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    owner_user_id: null,
    source_type: "system",
    title: "不怕上台的小刺猬",
    summary: "从朋友的鼓励里找到勇气，适合课堂主题和情绪引导。",
    cover_url: null,
    age_range_ids: [2],
    theme_ids: [2],
    education_goal_ids: [2],
    language: "zh",
    access_level: "free",
    publish_status: "published",
    view_count: 860,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    owner_user_id: null,
    source_type: "system",
    title: "星星为什么会眨眼",
    summary: "轻科普故事，适合中英双语启蒙和亲子提问。",
    cover_url: null,
    age_range_ids: [3],
    theme_ids: [4],
    education_goal_ids: [3],
    language: "bilingual",
    access_level: "vip",
    publish_status: "published",
    view_count: 640,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
