import { type BookDetail, type BookSummary } from "@/entities/book";

export const demoBooks: BookSummary[] = [
  {
    id: 1,
    title: "月亮邮局",
    subtitle: "一封写给夜晚的信",
    summary: "小狐狸在月光下帮大家投递心愿信，学会表达想念和感谢。",
    cover_url: null,
    age_range_ids: [2],
    theme_ids: [1, 3],
    education_goal_ids: [1],
    tags: ["睡前", "情绪表达"],
    language: "bilingual",
    reading_level: "L1",
    page_count: 10,
    duration_seconds: 480,
    access_level: "free",
    play_count: 12890,
    favorite_count: 982,
  },
  {
    id: 2,
    title: "森林里的小裁缝",
    subtitle: "把勇气缝进披风",
    summary: "胆小的小刺猬为朋友们做衣服，也为自己找到面对舞台的勇气。",
    cover_url: null,
    age_range_ids: [2],
    theme_ids: [2],
    education_goal_ids: [2],
    tags: ["勇气", "朋友"],
    language: "zh",
    reading_level: "L1",
    page_count: 8,
    duration_seconds: 390,
    access_level: "free",
    play_count: 8362,
    favorite_count: 641,
  },
  {
    id: 3,
    title: "星星采集员",
    subtitle: "一趟温柔的科学冒险",
    summary: "女孩和爷爷观察星空，在冒险里认识光、距离和家人的陪伴。",
    cover_url: null,
    age_range_ids: [3],
    theme_ids: [4],
    education_goal_ids: [3],
    tags: ["科普", "亲子"],
    language: "bilingual",
    reading_level: "L2",
    page_count: 12,
    duration_seconds: 620,
    access_level: "vip",
    play_count: 15240,
    favorite_count: 1250,
  },
  {
    id: 4,
    title: "会唱歌的云朵",
    subtitle: "天气也有小情绪",
    summary: "云朵学着用雨、风和阳光说话，孩子也学会识别自己的心情。",
    cover_url: null,
    age_range_ids: [2],
    theme_ids: [3],
    education_goal_ids: [4],
    tags: ["情绪管理", "自然"],
    language: "zh",
    reading_level: "L1",
    page_count: 9,
    duration_seconds: 430,
    access_level: "vip",
    play_count: 6844,
    favorite_count: 533,
  },
  {
    id: 5,
    title: "太阳面包店",
    subtitle: "分享让早餐更香",
    summary: "小熊开了一家只在清晨营业的面包店，慢慢理解分享和规则。",
    cover_url: null,
    age_range_ids: [2],
    theme_ids: [5],
    education_goal_ids: [5],
    tags: ["习惯养成", "分享"],
    language: "zh",
    reading_level: "L1",
    page_count: 8,
    duration_seconds: 360,
    access_level: "free",
    play_count: 9340,
    favorite_count: 712,
  },
];

export const demoBookDetail: BookDetail = {
  ...demoBooks[0],
  publish_status: "published",
  is_featured: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  source_story_id: 1,
  narrative_style_id: 1,
  art_style_id: 1,
  related_books: demoBooks.slice(1),
};
